name: dattings
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  firebase_auth: ^3.4.1
  email_validator: ^2.0.1
  shimmer: ^2.0.0
  get: ^4.6.5
  flutter_staggered_grid_view: ^0.4.1
  shared_preferences: ^2.0.15
  cloud_firestore: ^3.2.1
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.18
  file_picker: ^3.0.4
  intl: ^0.17.0
  firebase_database: ^9.0.18
  path_provider: ^2.0.11
  faker: ^2.0.0
  uuid: ^3.0.6
  provider: ^6.0.3
  keyboard_actions: ^4.0.1
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - images/
