class User {
  final String name;
  final String imageUrl;

  const User({
    required this.name,
    required this.imageUrl,
  });

}

// ignore: prefer_const_constructors
final User currentUser = User(
  name: 'Anh Báo',
  imageUrl:
      'https://toanthaydinh.com/wp-content/uploads/2020/04/top-nhung-hinh-anime-cuc-ngau-cho-nam-va-nu-anime-chat-11-2.png',
);

class Data {
  final String image,
      name,
      age,
      address,
      sex,
      marriage,
      likeCount,
      commentCount,
      content,
      countFollowing,
      countFollower,
      countLike,
      height,
      linkFb,
      linkInstagram,
      zlPhone,
      job,
      income,
      children,
      home,
      zodiac,
      target,
      status,
      formality;

  final int id;
  Data({
    required this.id,
    required this.image,
    required this.name,
    required this.age,
    required this.address,
    required this.sex,
    required this.marriage,
    required this.likeCount,
    required this.commentCount,
    required this.content,
    required this.countFollower,
    required this.countFollowing,
    required this.countLike,
    required this.height,
    required this.linkFb,
    required this.linkInstagram,
    required this.zlPhone,
    required this.job,
    required this.income,
    required this.children,
    required this.home,
    required this.zodiac,
    required this.target,
    required this.status,
    required this.formality,
  });
}

List<Data> data = [
  Data(
    id: 1,
    image: 'assets/images/avatar.jpg',
    name: 'Sakthi',
    sex: 'Nữ',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayamsd',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 2,
    image: 'assets/images/chopper.jpg',
    name: 'Sakthi',
    sex: 'Nam',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 3,
    image: 'assets/images/Luffy.jpg',
    name: 'Sakthi',
    sex: 'Nam',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 4,
    image: 'assets/images/avatar.jpg',
    name: 'Sakthi',
    sex: 'Nam',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkInstagram: 'https://www.instagram.com/',
    linkFb: 'https://www.facebook.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 5,
    image: 'assets/images/chopper.jpg',
    name: 'Sakthi',
    sex: 'Nam',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 6,
    image: 'assets/images/avatar.jpg',
    name: 'Sakthi',
    sex: 'Nam',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 7,
    image: 'assets/images/avatar.jpg',
    name: 'Sakthi',
    sex: 'Nam',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 8,
    image: 'assets/images/avatar.jpg',
    name: 'Sakthi',
    sex: 'Nữ',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 9,
    image: 'assets/images/avatar.jpg',
    name: 'Sakthi',
    sex: 'Nam',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
  Data(
    id: 10,
    image: 'assets/images/avatar.jpg',
    name: 'Sakthi',
    sex: 'Nam',
    age: '20',
    marriage: 'Đang yêu',
    address: 'Kottayam',
    likeCount: '2000',
    commentCount: '1000',
    content: 'I Love You',
    countFollower: '10',
    countFollowing: '20',
    countLike: '30',
    height: '1m80',
    linkFb: 'https://www.facebook.com/',
    linkInstagram: 'https://www.instagram.com/',
    zlPhone: '0989898989',
    job: 'Nhân viên',
    income: '1000000',
    children: '1',
    home: 'A',
    zodiac: 'Tử',
    target: 'B',
    status: 'C',
    formality: 'D',
  ),
];
